### ISSUE TITLE
Trouble with 3 modules

### ISSUE THREAD

**Issue by bennn** [mvitousek/reticulated#12]
If you have 3 modules like these, running `retic C.py` fails. The trouble seems to be importing the same type name from 2 different modules.
@migeed-z @mfelleisen

##### A.py
```
class A:
  pass
```

##### B.py
```
from A import A
class B:
  def yolo(a: A):  # Works if you remove the type annotation
    return a
```

##### C.py
```
from A import A
from B import B  # Works if you remove this import
class C:
  def wepa(a: A):
    return a
```

**Comment by mvitousek** [comment]
Confirmed, looking into.

**Comment by mvitousek** [comment]
Fixed, thanks for the report! Let me know if you have further problems.

**Comment by bennn** [comment]
Thank you!
